version: '2'

services:
    db:
        image: mysql
        volumes:
            - "./docker/mysql/data:/var/lib/mysql"
        env_file:
            - .env
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_USER: ${DATABASE_USER}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    php:
        build:
            context: ./docker/php-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        env_file:
            - .env
        environment:
            XDEBUG_CONFIG: ${XDEBUG_CONFIG}
            PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
        volumes:
            - ${APP_PATH}:/var/www/application:cached
            - ./docker/logs/app:/var/www/application/var/logs
    nginx:
        build: ./docker/nginx
        ports:
            - 8080:80
        volumes_from:
            - php
        volumes:
            - ./docker/logs/nginx:/var/log/nginx