imports:
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: ru

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%env(SYMFONY_SECRET)%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        -   bootstrap_3_layout.html.twig

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%env(DATABASE_HOST)%"
        port:     "%env(DATABASE_PORT)%"
        dbname:   "%env(DATABASE_NAME)%"
        user:     "%env(DATABASE_USER)%"
        password: "%env(DATABASE_PASSWORD)%"
        charset:  utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        mappings:
            User:
                type: annotation
                dir: "%kernel.root_dir%/../src/AppBundle/User/Entity"
                prefix: AppBundle\User\Entity
                alias: User
                is_bundle: false
            Category:
                type: annotation
                dir: "%kernel.root_dir%/../src/AppBundle/Category/Entity"
                prefix: AppBundle\Category\Entity
                alias: Category
                is_bundle: false
            Post:
                type: annotation
                dir: "%kernel.root_dir%/../src/AppBundle/Post/Entity"
                prefix: AppBundle\Post\Entity
                alias: Post
                is_bundle: false
            Tag:
                type: annotation
                dir: "%kernel.root_dir%/../src/AppBundle/Tag/Entity"
                prefix: AppBundle\Tag\Entity
                alias: Tag
                is_bundle: false
        filters:
            select_only_active:
                class: AppBundle\Common\Doctrine\Filters\SelectOnlyActive
                enabled: true

swiftmailer:
    transport:  "%env(MAILER_TRANSPORT)%"
    host:       "%env(MAILER_HOST)%"
    port:       "465"
    encryption: "ssl"
    username:   "%env(MAILER_USER)%"
    password:   "%env(MAILER_PASSWORD)%"
    spool:      { type: memory }

stof_doctrine_extensions:
    orm:
        default:
            sluggable: true
            timestampable: true
