homepage:
    path: /
    methods: [GET]

login:
    path: /login
    methods: [GET, POST]
    defaults: { _controller: AppBundle\Action\Login }

logout:
    path: /logout
    defaults: { _controller: AppBundle\Action\Logout }

registration:
    path: /registration
    defaults: { _controller: AppBundle\Action\Registration }
