parameters:

services:
    app.action.login:
        class: AppBundle\Action\Login
        arguments:
            - '@security.authentication_utils'
            - '@form.factory'
            - '@app.responder.login'

    app.responder.login:
        class: AppBundle\Responder\LoginResponder
        arguments: ['@templating']

    app.responder.registration:
        class: AppBundle\Responder\RegistrationResponder
        arguments: ['@templating']

    app.action.logout:
        class: AppBundle\Action\Logout

    app.action.registration:
        class: AppBundle\Action\Registration
        arguments:
            - '@form.factory'
            - '@app.responder.registration'
            - '@app.registration_form_handler'

    app.security.login_form_authenticator:
        class: AppBundle\Domain\Security\LoginFormAuthenticator
        autowire: true

    app.registration_form_handler:
        class: AppBundle\Domain\FormHandler\RegistrationTypeHandler
