parameters:

services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
#        exclude: '../../src/AppBundle/{Entity, Repository}'

    # repositories
    AppBundle\Domain\Repository\UserRepository:
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - 'AppBundle:User'
            - '@templating'

    # listeners
    AppBundle\Common\Doctrine\EventListener\HashPasswordSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    AppBundle\User\Registration\Handler\UserRegistration:
        public: true
        tags:
            - { name: command_handler, handles: AppBundle\User\Registration\Command\UserRegistration }

    AppBundle\User\Registration\Handler\UserActivation:
        public: true
        tags:
            - { name: command_handler, handles: AppBundle\User\Registration\Command\UserActivation }

    AppBundle\Common\Doctrine\EventListener\DomainEventsSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    AppBundle\User\EventListener\SendActivationCodeSubscriber:
        tags:
            - { name: kernel.event_subscriber }

#    AppBundle\Common\EventListener\RequestListener:
#        tags:
#            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
