parameters:

services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Common,User}'

    # repositories
    AppBundle\Domain\Repository\UserRepository:
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - 'AppBundle:User'

    # listeners
    AppBundle\Common\EventListener\Doctrine\HashPasswordSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

#    AppBundle\Command\Handler\UserLoginHandler:
#        tags:
#            - { name: command_handler, handles: AppBundle\Command\UserLogin }

    AppBundle\Common\EventListener\Doctrine\DomainEventsSubscriber:
        tags:
            - { name: doctrine.event_subscriber }
