parameters:
    upload_dir: '%kernel.root_dir%/../web/upload'

services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        #exclude: '../../src/AppBundle/{DataFixtures, Category}'
        exclude: '../../src/AppBundle/{Category/Entity,Tag/Entity,DataFixtures}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        tags: ['controller.service_arguments']

#    AppBundle\Common\Repository\Implementation\Repository:
#        abstract: true
#
#    AppBundle\User\Repository\Implementation\Users:
#        parent: AppBundle\Common\Repository\Implementation\Repository

    # listeners
    AppBundle\Common\Doctrine\EventListener\HashPasswordSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    AppBundle\User\Registration\Handler\UserRegistration:
        public: true
        tags:
            - { name: command_handler, handles: AppBundle\User\Registration\Command\UserRegistration }

    AppBundle\User\Registration\Handler\UserActivation:
        public: true
        tags:
            - { name: command_handler, handles: AppBundle\User\Registration\Command\UserActivation }

    AppBundle\Common\Doctrine\EventListener\DomainEventsSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    AppBundle\Post\EventListener\MarkdownToHTMLSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    AppBundle\User\EventListener\SendActivationCodeSubscriber:
        tags:
            - { name: kernel.event_subscriber }

#    AppBundle\Common\EventListener\RequestListener:
#        tags:
#            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    AppBundle\Common\Service\Implementation\FileUpload:
        arguments: ['%upload_dir%']
