parameters:

services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

#    AppBundle\:
#        resource: '../../src/AppBundle/*'
#        exclude: '../../src/AppBundle/Domain/{Entity,Repository}'

    # actions
    AppBundle\Action\Login:
        public: true

    AppBundle\Action\Logout:
        public: true

    AppBundle\Action\Registration:
        public: true

    # responders

    AppBundle\Responder\LoginResponder:
        public: true

    AppBundle\Responder\RegistrationResponder:
        public: true

    # form handlers
    AppBundle\Domain\FormHandler\FormTypeHandler: ~

    # security
    AppBundle\Domain\Security\LoginFormAuthenticator: ~

    # repositories
    AppBundle\Domain\Repository\UserRepository:
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - 'AppBundle:User'

    # listeners
    AppBundle\Domain\Doctrine\HashPasswordListener:
        tags:
            - { name: doctrine.event_subscriber }
