parameters:

services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository}'

    # actions
    AppBundle\Action\Login:
        public: true

    AppBundle\Action\Logout:
        public: true

    AppBundle\Action\Registration:
        public: true

    # responders

    AppBundle\Responder\LoginResponder:
        public: true

    AppBundle\Responder\RegistrationResponder:
        public: true

    # form handlers
    AppBundle\Domain\FormHandler\RegistrationTypeHandler: ~

    # security
    AppBundle\Domain\Security\LoginFormAuthenticator: ~
